# Generated by Django 4.0.4 on 2022-05-28 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import note.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('note', models.TextField(verbose_name='Текст заметки')),
                ('status', models.CharField(choices=[('AC', 'Активно'), ('PO', 'Отложено'), ('CO', 'Выполнено')], default='AC', max_length=2, verbose_name='Статус')),
                ('important', models.BooleanField(default=False, verbose_name='Важно')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('complete_time', models.DateTimeField(default=note.models.complete_time, verbose_name='Срок выполнения')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
